EmlakUI/Controllers/MoreController.cs
using BusinessLayer.Abstract;
using Microsoft.AspNetCore.Mvc;

namespace EmlakUI.Controllers
{
    public class MoreController : Controller
    {
        private readonly IAdvertService advertService;
        private readonly IImagesService imagesService;
        private readonly ICityService cityService;
        private readonly IDistrictService districtService;
        private readonly ITypeService typeService;
        private readonly IUsersService usersService;

        public MoreController(IAdvertService advertService, IImagesService imagesService,
            ICityService cityService, IDistrictService districtService, ITypeService typeService, IUsersService usersService)
        {
            this.advertService = advertService;
            this.imagesService = imagesService;
            this.cityService = cityService;
            this.districtService = districtService;
            this.typeService = typeService;
            this.usersService = usersService;
        }

        public async Task<IActionResult> Index(int id)
        {
            var advert = await advertService.BL_ReadAsync(id);

            var imgListInAdvert = await imagesService.BL_ListAsync(x => x.AdvertId == id);

            var city = await cityService.BL_ReadAsync(advert.CityId);
            var district = await districtService.BL_ReadAsync(advert.DistrictId);
            var type = await typeService.BL_ReadAsync(advert.TypeId);

            var user = await usersService.BL_ReadStringId(advert.UserAdminId);

            advert.UserAdmin = user;
            advert.Type = type;
            advert.City = city;
            advert.District = district;
            advert.Images = imgListInAdvert.ToList();
            
            return View(advert);
        }
    }
}

EmlakUI/Views/Shared/Components/ScrollRentPropertyInHome/Default.cshtml
@model List<EntityLayer.Entities.Advert>

@foreach (var item in Model)
{
    <div class="item">
        <div class="grids4-info">
            <a href="#"><img style="object-fit: cover; height:220px; width:100%" class="img-fluid" src="~/Pictures/@item.Images.First().ImageUrl" alt="" /></a>
            <div class="info-bg">
                <h5 style="font-weight:bold">@item.Title</h5>
                <span class="price">
                    <span style="color: #FB5607">₼</span> @item.Price<span style="color: #FB5607"> / </span> @item.PriceType
                </span>
                <p>@item.Description</p>
                <ul style="display:flex;justify-content:space-between;align-items:center;">
                    <li><span class="fa fa-bed"></span> @item.NumberOfRooms</li>
                    <li><i class="fa fa-building" style="color: #FB5607"></i> @item.Floor /@item.fullFloor</li>
                    <li><i class="fa fa-area-chart" style="color: #FB5607"></i> @item.Area m²</li>
                    <li><a class="btn" asp-controller="More" asp-action="Index" asp-route-id="@item.Id">Ətraflı</a></li>
                </ul>
            </div>
        </div>
    </div>
}