EmlakUI/Areas/Admin/Controllers/DistrictController.cs
using BusinessLayer.Abstract;
using EntityLayer.Entities;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace EmlakUI.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Policy = "AdminPolicy")]
    public class DistrictController : Controller
    {
        private readonly IDistrictService _districtService;
        private readonly ICityService _cityService;

        public DistrictController(IDistrictService districtService, ICityService cityService)
        {
            _districtService = districtService;
            _cityService = cityService;
        }

        public async Task<IActionResult> Index()
        {
            var districtList = await _districtService.BL_ListAsync("City");
            return View(districtList);
        }

        public async Task<List<City>> Cities()  
        {
            var cityList = await _cityService.BL_ListAsync(x => x.Status == true);
            return cityList;
        }

        public async Task DropDown()
        {
            var cities = await Cities();
            ViewBag.cityList = new SelectList(cities, "Id", "Name");
        }
        //Add new District

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            await DropDown();
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(District data)
        {
            if (ModelState.IsValid)
            {
                data.Status = true;
                await _districtService.BL_CreateAsync(data);
                TempData["addDistrict"] = "New District Added";
                return RedirectToAction(nameof(Index));
            }
            var errors = ModelState.Values.SelectMany(x => x.Errors);
            ViewData["Errors"] = errors;
            await DropDown();
            return View(data);
        }

        //Delete District Process

        public async Task<IActionResult> Delete(int id)
        {
            var deleteRow = await _districtService.BL_ReadAsync(id);
            await _districtService.BL_DeleteAsync(deleteRow);
            return RedirectToAction(nameof(Index));
        }

        //Update District Process

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var upRow = await _districtService.BL_ReadAsync(id);
            await DropDown();
            return View(upRow);
        }

        [HttpPost]
        public async Task<IActionResult> Update(District upData)
        {
            if (ModelState.IsValid)
            {
                await _districtService.BL_UpdateAsync(upData);
                TempData["updateDistrict"] = "District Updated";
                return RedirectToAction(nameof(Index));
            }
            var errors = ModelState.Values.SelectMany(x => x.Errors);
            ViewData["Errors"] = errors;
            await DropDown();
            return View(upData);
        }
    }
}

EmlakUI/Areas/Admin/Views/District/Create.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding
@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

@model District

<h1>Create New District Page</h1>
<br />

@if (ViewData["Errors"] != null)
{
    var errors = (IEnumerable<ModelError>)ViewData["Errors"];
    foreach (var err in errors)
    {
        <div class="alert alert-danger">
            <p>@err.ErrorMessage</p>
        </div>
    }
}

<form method="post" style="margin-bottom:50px">
    <label>Associated City</label>
        <select asp-for="CityId" id="CityId" class="form-control" required>
            <option value="0">Select a City</option>
            @foreach (var item in ViewBag.cityList)
            {
                <option value="@item.Value">@item.Text</option>
            }
        </select>
    <br />

    <label>Name</label>
    <input type="text" asp-for="Name" class="form-control" />
    <br />

    <div class="buttons d-flex gap-3">
        <button type="submit" class="btn btn-primary" style="width:80%">Add New District</button>
        <a asp-action="Index" asp-controller="District" class="btn btn-danger d-flex gap-1 align-items-center justify-content-center" style="width:20%">
            <i class="fa-solid fa-xmark"></i>Cancel
        </a>
    </div>
</form>

EmlakUI/Areas/Admin/Views/District/Index.cshtml
@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}
@model List<District>


<style>
    .pagetitle {
        position: relative;
        display: flex;
        justify-content: space-between;
    }

    .pagetitle_add_button {
        position: fixed;
        right: 25px;
        margin-top: 6px;
    }

    .pagetitle_text {
        position: fixed;
    }

    #table-container {
        position: relative;
        overflow-x: auto;
        max-width: 100%;
        margin-top: 70px;
    }

    #table td:first-child {
        position: sticky;
        left: -1px;
        z-index: 2;
    }

    .activeSpan {
        padding: 3px;
        border-radius: 7px;
        background-color: green;
        color: #fff;
        font-size: 15px;
    }

    .passiveSpan {
        padding: 3px;
        border-radius: 7px;
        background-color: red;
        font-size: 15px;
        color: #fff;
    }

    .button {
        position: relative;
        width: 202px;
        height: 45px;
        cursor: pointer;
        display: flex;
        align-items: center;
        border: 1px solid #395886;
        border-radius: 10px;
        background-color: #628ECB;
        transition: 0.2s;
    }

    .button, .button__icon, .button__text {
        transition: all 0.3s;
    }

        .button .button__text {
            transform: translateX(30px);
            color: #fff;
            font-weight: 600;
        }

        .button .button__icon {
            position: absolute;
            transform: translateX(164px);
            height: 100%;
            width: 39px;
            background-color: #395886;
            display: flex;
            align-items: center;
            border-radius: 10px;
            justify-content: center;
        }

        .button .svg {
            width: 30px;
            stroke: #fff;
        }

        .button:hover {
            background: #395886;
        }

            .button:hover .button__text {
                color: transparent;
            }

            .button:hover .button__icon {
                width: 164px;
                transform: translateX(20px);
            }

        .button:active {
            transform: scale(0.9);
        }
</style>
@if (TempData["newDistrictSuccess"] != null)
{
    <script>
        iziToast.settings({
            timeout: 3000,
            resetOnHover: false,
            icon: 'material-icons',
            transitionIn: 'flipInX',
            transitionOut: 'flipOutX',
        });

        iziToast.success({
            icon: 'fa-solid fa-check',
            title: 'Added! ',
            message: '@TempData["newDistrictSuccess"]',
        });
    </script>
}
@if (TempData["updateDistrict"] != null)
{
    <script>
        iziToast.settings({
            timeout: 3000,
            resetOnHover: false,
            icon: 'material-icons',
            transitionIn: 'flipInX',
            transitionOut: 'flipOutX',
        });

        iziToast.success({
            icon: 'fa-solid fa-check',
            title: 'Updated! ',
            message: '@TempData["updateDistrict"]',
        });
    </script>
}

<div class="pagetitle">
    <div class="pagetitle_text">
        <h1>All Districts</h1>
        <nav>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="index.html">Home</a></li>
                <li class="breadcrumb-item active">All Districts</li>
            </ol>
        </nav>
    </div>
    <div class="pagetitle_add_button">
        <a type="button" class="button" asp-area="Admin" asp-controller="District" asp-action="Create">
            <span class="button__text">Add New District</span>
            <span class="button__icon"><svg xmlns="http://www.w3.org/2000/svg" width="24" viewBox="0 0 24 24" stroke-width="2" stroke-linejoin="round" stroke-linecap="round" stroke="currentColor" height="24" fill="none" class="svg"><line y2="19" y1="5" x2="12" x1="12"></line><line y2="12" y1="12" x2="19" x1="5"></line></svg></span>
        </a>
    </div>
</div>

<div id="table-container">
    <table class="table table-bordered display nowrap" id="table" style="width:100%">
        <thead>
            <tr>
                <th class="text-start" style="background-color:#395886; color:#ffff;">ID</th>
                <th style="background-color:#628ecb; color:#ffff">District Name</th>
                <th style="background-color:#628ecb; color:#ffff">Associated City</th>
                <th style="background-color:#628ecb; color:#ffff">Status</th>
                <th style="background-color:#acffa1">Update</th>
                <th style="background-color:#ffa1a1">Delete</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-start" style="background-color:#d5deef">@item.Id</td>
                    <td class="short">@item.Name</td>
                    <td class="short">@item.City.Name</td>
                    <td class="short text-center">
                        @if (item.Status)
                        {
                            <span class="activeSpan">Active</span>
                        }
                        else
                        {
                            <span class="passiveSpan">Passive</span>
                        }
                    </td>
                    <td><a asp-controller="District" asp-action="Update" asp-route-id="@item.Id" class="btn btn-success"><i class="fa-solid fa-pen-to-square"></i></a></td>
                    <td><a data-id="@item.Id" class="btn btn-danger deletebtn"><i class="fa-solid fa-trash"></i></a></td>
                </tr>
            }
        </tbody>
    </table>
</div>
<link rel="stylesheet" href="https://cdn.datatables.net/2.0.8/css/dataTables.dataTables.css" />
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="https://cdn.datatables.net/2.0.8/js/dataTables.js"></script>
<script>

    $(document).ready(function () {
        $("#table").on("click", ".deletebtn", function () {
            Swal.fire({
                title: 'Emin misiniz?',
                text: "Bu işlemi geri alamazsınız!",
                icon: 'warning',
                showCancelButton: true,
                confirmButtonColor: '#3085d6',
                cancelButtonColor: '#d33',
                confirmButtonText: 'Evet, sil!',
                cancelButtonText: 'Hayır, iptal et'
            }).then((result) => {
                if (result.isConfirmed) {
                    var btn = $(this);
                    var id = btn.data("id");

                    $.ajax({

                        type: "GET",
                        url: "/Admin/District/Delete?id=" + id,
                        success: function () {
                            btn.parent().parent().remove();
                            iziToast.settings({
                                timeout: 3000,
                                resetOnHover: false,
                                icon: 'material-icons',
                                transitionIn: 'flipInX',
                                transitionOut: 'flipOutX',
                            });

                            iziToast.warning({
                                icon: 'fa-solid fa-check',
                                title: 'Deleted! ',
                                message: 'Successful',
                            });
                        }

                    });
                }
            });
        });
    })

    $(".table").DataTable({
        "lengthMenu": [[8, 10, 25, 50, -1], [8, 10, 25, 50, "All"]],
        "pageLength": 8,
        "scrollX": true,
    });


</script>

EmlakUI/Areas/Admin/Views/District/Update.cshtml
@using Microsoft.AspNetCore.Mvc.ModelBinding

@{
    ViewData["Title"] = "Update";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}


@model District
<style>


    .toggler input {
        display: none;
    }

    .toggler label {
        display: block;
        position: relative;
        width: 72px;
        height: 36px;
        border: 1px solid #d6d6d6;
        border-radius: 36px;
        background: #e4e8e8;
        cursor: pointer;
    }

        .toggler label::after {
            display: block;
            border-radius: 100%;
            background-color: #d7062a;
            content: '';
            animation-name: toggler-size;
            animation-duration: 0.15s;
            animation-timing-function: ease-out;
            animation-direction: forwards;
            animation-iteration-count: 1;
            animation-play-state: running;
        }

        .toggler label::after, .toggler label .toggler-on, .toggler label .toggler-off {
            position: absolute;
            top: 50%;
            left: 25%;
            width: 26px;
            height: 26px;
            transform: translateY(-50%) translateX(-50%);
            transition: left 0.15s ease-in-out, background-color 0.2s ease-out, width 0.15s ease-in-out, height 0.15s ease-in-out, opacity 0.15s ease-in-out;
        }

    .toggler input:checked + label::after, .toggler input:checked + label .toggler-on, .toggler input:checked + label .toggler-off {
        left: 75%;
    }

    .toggler input:checked + label::after {
        background-color: #50ac5d;
        animation-name: toggler-size2;
    }

    .toggler .toggler-on, .toggler .toggler-off {
        opacity: 1;
        z-index: 2;
    }

    .toggler input:checked + label .toggler-off, .toggler input:not(:checked) + label .toggler-on {
        width: 0;
        height: 0;
        opacity: 0;
    }

    .toggler .path {
        fill: none;
        stroke: #fefefe;
        stroke-width: 7px;
        stroke-linecap: round;
        stroke-miterlimit: 10;
    }

    @@keyframes toggler-size {
        0%, 100% {
            width: 26px;
            height: 26px;
        }

        50% {
            width: 20px;
            height: 20px;
        }
    }

    @@keyframes toggler-size2 {
        0%, 100% {
            width: 26px;
            height: 26px;
        }

        50% {
            width: 20px;
            height: 20px;
        }
    }
</style>
<h1>Update District Page</h1>
<br />

@if (ViewData["Errors"] != null)
{
    var errors = (IEnumerable<ModelError>)ViewData["Errors"];
    foreach (var err in errors)
    {
        <div class="alert alert-danger">
            <p>@err.ErrorMessage</p>
        </div>
    }
}

<form method="post" style="margin-bottom:50px">
    <label>Associated City</label>
    <select asp-for="CityId" id="CityId" class="form-control" required>
        <option value="0">Select a City</option>
        @foreach (var item in ViewBag.cityList)
        {
            <option value="@item.Value">@item.Text</option>
        }
    </select>
    <br />

    <label>Name</label>
    <input type="text" asp-for="Name" class="form-control" />
    <br />
    <div style="display: flex; align-items: center; gap:20px">
        <label>Status</label>
        <div class="toggler">
            <input id="toggler-1" asp-for="Status" type="checkbox">
            <label for="toggler-1">
                <svg class="toggler-on" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2">
                    <polyline class="path check" points="100.2,40.2 51.5,88.8 29.8,67.5"></polyline>
                </svg>
                <svg class="toggler-off" version="1.1" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 130.2 130.2">
                    <line class="path line" x1="34.4" y1="34.4" x2="95.8" y2="95.8"></line>
                    <line class="path line" x1="95.8" y1="34.4" x2="34.4" y2="95.8"></line>
                </svg>
            </label>
        </div>
    </div>
    <br />
    <br />

    <div class="buttons d-flex gap-3">
        <button type="submit" class="btn btn-primary" style="width:80%">Update District</button>
        <a asp-action="Index" asp-controller="District" class="btn btn-danger d-flex gap-1 align-items-center justify-content-center" style="width:20%">
            <i class="fa-solid fa-xmark"></i>Cancel
        </a>
    </div>
</form>